name: Transcribe

on: [push]

steps:
- uses: actions/checkout@master
- uses: actions/setup-node@v1
  with:
    node-version: '10.x'
- run: |
    npm install
    npm run start:transcribe
    ls ./src/transcribe-and-align/sample
